
<div class="row">
	
	<div class="row">
		<?= ReviewData::getError($this->request->get('error') ?? '') ?>
	</div>

	
	<form action="/review/process" method="post">

	<div class="form-group">
		<label for="name">Are you interested in development?</label>
	</div>
	
	<div class="form-group form-inline">
	  <label class="form-check-label">
		<input class="form-check-input" type="radio" name="devInetrest" id="devInetrestYes" value="Yes"> Yes
	  </label>
	
	
	  <label class="form-check-label">
		<input class="form-check-input" type="radio" name="devInetrest" id="devInetrestNo" value="No"> No
	  </label>
	
	</div>
	<div>
		<input type="hidden" name="question" value="<?= $question ?>" />
	</div>
	<br />
	
	<div class="form-group right">
		<input class="btn btn-primary" type="submit" value="Continue">
	</div>
	
	</form>


</div>