
<div class="row">
	
	<div class="row">
		<?= ReviewData::getError($this->request->get('error') ?? '') ?>
	</div>

	
	<form action="/review/process" method="post">

	<div class="form-group">
		<label for="name">Are you interested in development?</label>
	</div>
	
	<div class="form-group">
	  <div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input dev" name="softDev[]" value="php">
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">PHP</span>
		  </label>
		</div>
		<div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input dev" name="softDev[]" value="css">
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">CSS</span>
		  </label>
		</div>
		
		<div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input dev" name="softDev[]" value="html">
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">HTML</span>
		  </label>
		</div>
		<div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input dev" name="softDev[]" value="javascript">
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">JavaScript</span>
		  </label>
		</div>
		
		<div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input dev" name="softDev[]" value="java">
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">Java</span>
		  </label>
		</div>
		<div class="form-group">
		  <label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input noDev" name="softDev[]" value="noDev" />
			<span class="custom-control-indicator"></span>
			<span class="custom-control-description">Don’t know any</span>
		  </label>
		</div>
	
	</div>
	<div>
		<input type="hidden" name="question" value="<?= $question ?>" />
	</div>
	<br />
	
	<div class="form-group right">
		<input class="btn btn-primary" type="submit" value="Continue">
	</div>
	
	</form>


</div>