
<div class="row">

	<div class="row">
		<?= ReviewData::getError($this->request->get('error') ?? '') ?>
	</div>

	<form action="/review/process" method="post">

	<div class="form-group">
		<label for="name">What is your name?</label>
		<input type="text" class="form-control" name="name" id="name">
	</div>
	<div>
		<input type="hidden" name="question" value="<?= $question ?>" />
	</div>
	<br />
	
	<div class="form-group right">
		<input class="btn btn-primary" type="submit" value="Continue">
	</div>
	
	</form>


</div>