
<div class="row">
	
	<div class="row">
		<?= ReviewData::getError($this->request->get('error') ?? '') ?>
	</div>

	
	<form action="/review/process" method="post">

	<div class="form-group">
		<label for="dob">Your birth date:</label>
	</div>
	<div class="form-group form-inline">
		
		 <select class="form-control" id="day" name="day">
			<option value="">Day</option>
			<?php for($day = 1; $day<=31; $day++) { ?>
			<option value='<?= $day ?>'><?= $day ?></option>
			<?php } ?>
		  </select>
		  
		  <select class="form-control" id="month" name="month">
			<option selected value=''> Month </option>
			<option value='1'>Janaury</option>
			<option value='2'>February</option>
			<option value='3'>March</option>
			<option value='4'>April</option>
			<option value='5'>May</option>
			<option value='6'>June</option>
			<option value='7'>July</option>
			<option value='8'>August</option>
			<option value='9'>September</option>
			<option value='10'>October</option>
			<option value='11'>November</option>
			<option value='12'>December</option>
		  </select>
		  
		  <select class="form-control" id="year" name="year">
			<option value="">Year</option>
			<?php for($day = 1990; $day<=2017; $day++) { ?>
			<option value='<?= $day ?>'><?= $day ?></option>
			<?php } ?>
		  </select>
	</div>
	<div>
		<input type="hidden" name="question" value="<?= $question ?>" />
	</div>
	<br />
	
	<div class="form-group right">
		<input class="btn btn-primary" type="submit" value="Continue">
	</div>
	
	</form>


</div>